# Generated by Django 5.2.4 on 2025-08-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_cnpj', models.CharField(max_length=8, unique=True)),
                ('corporate_name', models.CharField(max_length=200)),
                ('legal_nature', models.CharField(max_length=3)),
                ('responsible_qualification', models.CharField(max_length=2)),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('company_size', models.CharField(max_length=1)),
                ('federative_entity', models.CharField(max_length=1)),
            ],
        ),
    ]
