# Generated by Django 5.2.4 on 2025-08-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('acronym', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=32)),
            ],
        ),
    ]
